name: Generate Documentation

on:
  push:
    branches:
      - master # Adjust to your main branch name

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4 # Adjust to your PHP version

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        export PATH="$HOME/.config/composer/vendor/bin:$PATH"

    - name: Install phpDocumentor
      run: |
        composer global require phpdocumentor/phpdocumentor
        export PATH="$HOME/.config/composer/vendor/bin:$PATH"

    - name: Generate Documentation
      run: phpdoc run -d ./src -t ./docs

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit Documentation
      run: |
        git add ./docs
        git commit -m "Update documentation"
        git push

    - name: Complete
      run: echo "Documentation generated and pushed."
